version: "3"

services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "${SWAGGER_PORT}:8080"
  static-server:
    image: nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "${SWAGGER_HOME}:/public"